Change how if statements are structured in Travis CI file

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,17 +23,15 @@ script:
     --mount type=bind,source="$(pwd)"/test,destination=/test
     edwardotme/raspbian-customiser:$TRAVIS_BRANCH
   # Stop here if this fails
-  - |
-    if [ $? -ne 0 ]; then
-      echo "FAILURE - Testing Docker container failed"
-      exit 1
+  - if [ $? -ne 0 ]; then
+      echo "FAILURE - Testing Docker container failed";
+      exit 1;
     fi
     echo "SUCCESS - Testing was successful"
   # If this is the master branch an the test passes, add the 'stable' tag and push to the registry
-  - |
-    if [ $TRAVIS_BRANCH == "master" ]; then
-      echo "DEPLOY - Will now push Docker image to Docker Hub"
-      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
-      docker tag edwardotme/raspbian-customiser:$TRAVIS_BRANCH edwardotme/raspbian-customiser:stable
-      docker push edwardotme/raspbian-customiser:stable
+  - if [ $TRAVIS_BRANCH == "master" ]; then
+      echo "DEPLOY - Will now push Docker image to Docker Hub";
+      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
+      docker tag edwardotme/raspbian-customiser:$TRAVIS_BRANCH edwardotme/raspbian-customiser:stable;
+      docker push edwardotme/raspbian-customiser:stable;
     fi
